program diff;
{
Toy diff tool to compare object code generated by two builds of pcom

By Christophe Staiesse.

Compares two files line by line ignoring all blanks. Stops on first mismatch.

Usage: diff file1 file2

Note: doesn't compile with Pascal-P.
}
var
  f1, f2: Text;
  s1, s2: String;
  LineCount: Integer;

function CompLines(var s1, s2: String): Boolean;
  function RemoveBlanks(s: String): String;
  var
    i: Integer;
    d: string;
  begin
    d := '';
    for i := 1 to Length(s) do
      if s[i] > ' ' then
        d := d + s[i];
    RemoveBlanks := d;
  end;

begin
  CompLines := RemoveBlanks(s1) = RemoveBlanks(s2);
end;

begin
  Assign(f1, ParamStr(1));
  Reset(f1);
  Assign(f2, ParamStr(2));
  Reset(f2);

  LineCount := 0;

  while not Eof(f1) or not Eof(f2) do
    begin
      if Eof(f1) or Eof(f2) then
        begin
          WriteLn('Files differs in line count');
          Halt(1);
        end;

      ReadLn(f1,s1);
      ReadLn(f2,s2);

      LineCount := LineCount+1;

      if not CompLines(s1,s2) then
        begin
          WriteLn('Files differs at line ',LineCount);
          WriteLn(' file 1: ',s1);
          WriteLn(' file 2: ',s2);
          Halt(1);
        end;
    end
end.
